"""
ZMUX CLI — transparent Unix shell integration.

The executable wrappers generated by :func:`zmux.paths.ensure_cli_wrappers`
re-enter the Python runtime through this module::

    python -m zmux.cli <cmd> [args...]

Each wrapper forwards ``"$0"`` (its own invoked path) as the first argument,
so the typed command name is recovered with ``os.path.basename(argv[0])``.
This is kept as a small app-control compatibility layer. The user-facing
terminal is Alpine-first; package work should happen with ``apk`` and, for
Python projects, ``pip`` inside an Alpine virtual environment.
"""
from __future__ import annotations

import os
import shlex
import subprocess
import sys

from zmux.command_registry import (
    ACCEPTED_COMMANDS,
    DIAGNOSTIC_COMMANDS,
    LEGACY_ALIAS_COMMANDS,
    LEGACY_COMPAT_COMMANDS,
    PRIMARY_COMMANDS,
    WRAPPER_COMMANDS,
)

#: Commands with generated wrappers (mirrors zmux.paths.CLI_COMMANDS).
COMMANDS = WRAPPER_COMMANDS

_USAGE = (
    "usage: python -m zmux.cli <command> [args...]\n"
    f"active: {', '.join(PRIMARY_COMMANDS)}\n"
    f"diagnostics: {', '.join(DIAGNOSTIC_COMMANDS)}\n"
    f"legacy compat: {', '.join((*LEGACY_COMPAT_COMMANDS, *LEGACY_ALIAS_COMMANDS))}"
)

_PIP_FALLBACK = """Host-side pip is not part of the Alpine-first ZMUX workflow.
Open the Alpine terminal and install Python packages there instead:
  apk add python3 py3-pip py3-virtualenv
  python3 -m venv ~/.venv
  . ~/.venv/bin/activate
  python3 -m pip install <name>

Prefer Alpine packages first when they exist:
  apk search <name>
  apk add py3-<package>"""


def _legacy_notice(command: str) -> str:
    """Return a one-line retirement notice for legacy compatibility commands."""
    if command == "zpip":
        return (
            "zpip is legacy compatibility in Alpine-first ZMUX; "
            "prefer `apk search/add` or `python3 -m pip` inside an Alpine venv."
        )
    if command == "pip":
        return (
            "host-side pip is legacy compatibility; "
            "prefer Python packages inside an Alpine virtual environment."
        )
    if command in {"linux", "alpine"}:
        return (
            f"{command} is a legacy host wrapper; in the normal Alpine shell, "
            "run the command directly without the prefix."
        )
    return f"{command} is legacy compatibility."


def _warn_legacy(command: str) -> None:
    """Print a deprecation notice to stderr without changing stdout contracts."""
    print(f"WARNING: {_legacy_notice(command)}", file=sys.stderr)


def _cmd_help() -> int:
    """Print the formatted ZMUX terminal help text."""
    from zmux.terminal import HELP_TEXT
    sys.stdout.write(HELP_TEXT)
    if not HELP_TEXT.endswith("\n"):
        sys.stdout.write("\n")
    return 0


def _cmd_clear() -> int:
    """Clear the terminal: home cursor, clear screen and scrollback buffer."""
    sys.stdout.write("\033[H\033[2J\033[3J")
    return 0


def _cmd_setup_storage() -> int:
    """Grant and link shared Android storage into ~/storage."""
    from zmux import storage
    result = storage.setup()
    print(storage.format_setup(result))
    return 0 if result.get("ok") else 1


def _cmd_zmux_info() -> int:
    """Print the formatted ZMUX runtime fingerprint."""
    from zmux import runtime_info
    print(runtime_info.format_fingerprint(runtime_info.runtime_fingerprint()))
    return 0


def _cmd_zpip(args: list) -> int:
    """Run the legacy zpip command for compatibility."""
    _warn_legacy("zpip")
    from zmux import zpip
    command = "zpip" + (" " + shlex.join(args) if args else "")
    output, exit_code = zpip.format_output(command, zpip.dispatch(command))
    print(output)
    return exit_code


def _cmd_linux_setup(args: list) -> int:
    """Install (or repair) the proot'd Alpine userland."""
    from zmux import linuxenv
    try:
        result = linuxenv.install(progress=lambda text: sys.stdout.write(text))
    except Exception as error:
        print(f"linux-setup failed: {error}", file=sys.stderr)
        return 1
    print(f"Alpine {result.get('version', '?')} ready at {result.get('path')}")
    if (linuxenv.rootfs_dir() / "usr" / "bin" / "git").is_file():
        print("`git` is available. Try: git clone <url>")
    else:
        print("Enable git from the Alpine shell (one-time, needs network):")
        print("  apk add git openssh-client")
    return 0


def _cmd_linux(command: str, args: list) -> int:
    """Run a shell command inside the Alpine userland (legacy CLI entry)."""
    _warn_legacy(command)
    from zmux import linuxenv
    if not linuxenv.is_installed():
        print("Alpine environment is not installed. Run: linux-setup", file=sys.stderr)
        return 1
    if not args:
        print(f"usage: zmux {command} <command...>")
        print("In the normal Alpine shell, run commands directly, e.g.: apk add git")
        return 2
    try:
        guest_argv = ["/bin/sh", "-c", shlex.join(args)]
        cmdline = linuxenv.build_command_line(guest_argv, linuxenv.HOME_DIR)
    except RuntimeError as error:
        print(f"linux: {error}", file=sys.stderr)
        return 1
    env = dict(os.environ)
    env.update(linuxenv.proot_env())
    return subprocess.call(cmdline, shell=True, env=env)


def _cmd_gates(args: list) -> int:
    """Run the strict on-device acceptance probe (G1–G5)."""
    from zmux import linuxenv
    results = linuxenv.run_gates()
    passed = sum(1 for r in results.values() if r["ok"])
    return 0 if passed == len(results) else 1


def _cmd_pty_probe(args: list) -> int:
    """Run the real-PTY acceptance probe (pty1–pty6). Nothing is mocked."""
    from zmux import realpty
    results = realpty.run_pty_probe()
    passed = sum(1 for r in results.values() if r["ok"])
    return 0 if passed == len(results) else 1


def _cmd_pip(args: list) -> int:
    """Run standard host pip when available, otherwise print Alpine guidance."""
    executable = sys.executable or ""
    if executable and os.access(executable, os.X_OK):
        _warn_legacy("pip")
        try:
            return subprocess.call([executable, "-m", "pip", *args])
        except OSError:
            pass
    print(_PIP_FALLBACK)
    return 1


def main(argv=None) -> int:
    """CLI entrypoint. Returns the process exit code."""
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print(_USAGE, file=sys.stderr)
        return 2
    command = os.path.basename(argv[0])
    args = argv[1:]
    if command not in ACCEPTED_COMMANDS:
        print(f"zmux.cli: unknown command: {command}", file=sys.stderr)
        print(_USAGE, file=sys.stderr)
        return 127
    if command == "help":
        return _cmd_help()
    if command == "clear":
        return _cmd_clear()
    if command == "zmux-info":
        return _cmd_zmux_info()
    if command == "zmux-setup-storage":
        return _cmd_setup_storage()
    if command == "linux-setup":
        return _cmd_linux_setup(args)
    if command in ("linux", "alpine"):
        return _cmd_linux(command, args)
    if command == "gates":
        return _cmd_gates(args)
    if command == "zmux-pty-probe":
        return _cmd_pty_probe(args)
    if command == "zpip":
        return _cmd_zpip(args)
    if command == "pip":
        return _cmd_pip(args)
    print(f"zmux.cli: unknown command: {command}", file=sys.stderr)
    print(_USAGE, file=sys.stderr)
    return 127


if __name__ == "__main__":
    sys.exit(main())
