"""
ZMUX Path Resolution & Directory Management

Handles APP_DIR detection for Android and Desktop environments.
All runtime directories are app-private and gitignored.
"""

import os
import shlex
import stat
from pathlib import Path

from zmux.command_registry import WRAPPER_COMMANDS


def _is_writable(path: Path) -> bool:
    """Check if a directory can be created and written to."""
    try:
        path.mkdir(parents=True, exist_ok=True)
        test_file = path / ".zmux_write_test"
        test_file.write_text("ok", encoding="utf-8")
        test_file.unlink(missing_ok=True)
        return True
    except OSError:
        return False


def resolve_app_dir() -> Path:
    """
    Resolve the application directory based on runtime environment.
    
    Priority:
    1. ANDROID_PRIVATE / ANDROID_ARGUMENT / ANDROID_APP_PATH env vars (p4a webview bootstrap)
    2. Fallback: project root (where main.py lives) for desktop development
    3. Safe Android / POSIX writable fallbacks
    """
    for env_key in ("ANDROID_PRIVATE", "ANDROID_ARGUMENT", "ANDROID_APP_PATH"):
        val = os.environ.get(env_key)
        if val:
            candidate = Path(val)
            if _is_writable(candidate):
                return candidate

    default_root = Path(__file__).resolve().parent.parent
    if _is_writable(default_root):
        return default_root

    for candidate_str in (
        os.environ.get("HOME", ""),
        os.environ.get("TMPDIR", ""),
        "/data/local/tmp/zmux",
        "/cache/zmux",
        "/tmp/zmux",
    ):
        if candidate_str:
            candidate = Path(candidate_str)
            if _is_writable(candidate):
                return candidate

    return default_root


APP_DIR = resolve_app_dir()

# Core runtime directories — all app-private.
HOME_DIR = APP_DIR / "home"
PROJECTS_DIR = HOME_DIR / "projects"
CACHE_DIR = APP_DIR / "cache"
LOG_DIR = APP_DIR / "logs"
BIN_DIR = APP_DIR / "bin"

# Legacy ZABAWHEELS/zpip package-manager directories. Retained for migration,
# tests, and existing installs only; Alpine apk + venv/pip is the product
# package workflow.
DOWNLOADS_DIR = CACHE_DIR / "downloads"
STAGING_DIR = APP_DIR / "staging"
USER_PACKAGES_DIR = APP_DIR / "user_packages"
INSTALLED_DIR = APP_DIR / "installed"

CORE_RUNTIME_DIRS = (
    HOME_DIR,
    PROJECTS_DIR,
    CACHE_DIR,
    LOG_DIR,
    BIN_DIR,
)

LEGACY_PACKAGE_DIRS = (
    DOWNLOADS_DIR,
    STAGING_DIR,
    USER_PACKAGES_DIR,
    INSTALLED_DIR,
)

ALL_RUNTIME_DIRS = CORE_RUNTIME_DIRS + LEGACY_PACKAGE_DIRS

# Ensure all directories exist with restricted permissions (owner-only).
# On Android this keeps app-private data inaccessible to other apps and
# prevents accidental exposure via shared storage providers. Legacy package
# dirs are still created so old installs/tests keep working until removal.
for directory in ALL_RUNTIME_DIRS:
    directory.mkdir(parents=True, exist_ok=True)
    try:
        os.chmod(directory, stat.S_IRWXU)  # 0o700
    except OSError:
        pass



def legacy_package_paths() -> dict[str, Path]:
    """Return legacy package-manager paths for diagnostics/migration."""
    return {
        "downloads": DOWNLOADS_DIR,
        "staging": STAGING_DIR,
        "user_packages": USER_PACKAGES_DIR,
        "installed": INSTALLED_DIR,
    }


def legacy_user_packages_pythonpath(existing: str = "") -> str:
    """Prepend legacy ``USER_PACKAGES_DIR`` to a PYTHONPATH string."""
    entry = str(USER_PACKAGES_DIR)
    parts = [entry]
    if existing:
        parts.append(existing)
    return os.pathsep.join(parts)

# ---------------------------------------------------------------------------
# Transparent Unix shell integration
#
# The real Android PTY shell (/system/bin/sh) can only execute binaries and
# scripts that live on $PATH — typing "zpip", "help", "zmux-info", "clear" or
# "pip" otherwise fails with "/system/bin/sh: <cmd>: inaccessible or not found".
# ZMUX therefore auto-generates tiny executable wrappers inside BIN_DIR so the
# commands resolve natively in any /system/bin/sh session.
# ---------------------------------------------------------------------------

#: Commands that get an executable shell wrapper inside BIN_DIR. The registry
#: distinguishes supported app controls from legacy compatibility names.
CLI_COMMANDS = WRAPPER_COMMANDS

#: Wrapper template shared by every ZMUX command. Each script re-enters the
#: Python runtime via ``python -m zmux.cli "$0" "$@"`` so the typed command
#: name is recovered from the invoked path. ``PYTHONPATH`` is pinned to the
#: directory that contains the ``zmux`` package because child shells spawned
#: by app-private processes do not necessarily inherit it.
_CLI_WRAPPER_TEMPLATE = """#!/system/bin/sh
# ZMUX CLI wrapper — auto-generated by zmux.paths.ensure_cli_wrappers().
# Do not edit manually; this file is rewritten on every app start.
export PYTHONPATH={app_dir}"${{PYTHONPATH:+:$PYTHONPATH}}"
if command -v python >/dev/null 2>&1; then
    exec python -m zmux.cli "$0" "$@"
fi
if command -v python3 >/dev/null 2>&1; then
    exec python3 -m zmux.cli "$0" "$@"
fi
echo "zmux: Python runtime not found on PATH" >&2
exit 127
"""


def _prepend_to_path(directory: Path) -> None:
    """Prepend a directory to os.environ["PATH"] (idempotent)."""
    entry = str(directory)
    current = os.environ.get("PATH", "")
    parts = current.split(os.pathsep) if current else []
    if entry not in parts:
        os.environ["PATH"] = entry + (os.pathsep + current if current else "")


def ensure_cli_wrappers() -> Path:
    """
    (Re)generate the executable ZMUX shell wrappers inside BIN_DIR.

    Every wrapper is a ``#!/system/bin/sh`` script that execs
    ``python -m zmux.cli "$0" "$@"`` (falling back to ``python3`` when
    ``python`` is unavailable) and is chmod'ed 0o755. BIN_DIR is also
    prepended to ``os.environ["PATH"]`` so the current process and all of
    its children resolve the commands transparently.
    """
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    # Directory that contains the "zmux" package (importable via -m).
    package_root = Path(__file__).resolve().parent.parent
    content = _CLI_WRAPPER_TEMPLATE.format(app_dir=shlex.quote(str(package_root)))
    for name in CLI_COMMANDS:
        wrapper = BIN_DIR / name
        try:
            current = wrapper.read_text(encoding="utf-8") if wrapper.exists() else None
        except OSError:
            current = None
        if current != content:
            wrapper.write_text(content, encoding="utf-8", newline="\n")
        os.chmod(wrapper, 0o755)
    _prepend_to_path(BIN_DIR)
    return BIN_DIR


# Generate the wrappers and expose BIN_DIR on PATH at import time so the
# commands work from the very first PTY session. Never let a filesystem hiccup
# break app startup — the worst case is the legacy "not found" behaviour.
try:
    ensure_cli_wrappers()
except OSError:
    pass


# ---------------------------------------------------------------------------
# Small shared display/example helpers
# ---------------------------------------------------------------------------

def ensure_user_packages_importable() -> None:
    """Keep legacy ``USER_PACKAGES_DIR`` importable in host-side Python.

    ``zpip install`` writes there and old host-console/REST compatibility paths
    may still import those packages. Alpine-first user workflows should prefer
    ``apk`` and venv-local ``pip`` inside the guest instead. Idempotent; called
    at import time until the zpip runtime is removed.
    """
    import sys
    entry = str(USER_PACKAGES_DIR)
    if entry not in sys.path:
        # After "" / the script dir, so a local file still wins, but ahead of
        # the stdlib-adjacent entries that follow.
        sys.path.insert(1, entry)


ensure_user_packages_importable()


def display_path(cwd: Path, home: Path = HOME_DIR) -> str:
    """Render ``cwd`` relative to ``home`` (``~`` style) for prompt display."""
    try:
        rel = Path(cwd).resolve().relative_to(home.resolve())
        return "~" if str(rel) == "." else f"~/{rel}"
    except ValueError:
        return str(cwd)


#: First-boot example scripts (educational onboarding, Pydroid-style).
#: Kept tiny on purpose: each demonstrates one thing that actually works in
#: the ZMUX runtime today.
EXAMPLE_SCRIPTS: dict[str, str] = {
    "hello.py": (
        '"""ZMUX hello — plain Python running in the embedded runtime."""\n'
        'import platform\n\n'
        'print("Hello from ZMUX!")\n'
        'print("Python:", platform.python_version())\n'
    ),
    "files_demo.py": (
        '"""File APIs operate on the real app-private filesystem."""\n'
        'from pathlib import Path\n\n'
        'note = Path("notes.txt")\n'
        'note.write_text("ditulis dari ZMUX\\n", encoding="utf-8")\n'
        'print("isi notes.txt:", note.read_text(encoding="utf-8").strip())\n'
        'note.unlink()\n'
    ),
    "runtime_info_demo.py": (
        '"""See the ZMUX runtime fingerprint used by diagnostics."""\n'
        'import sys\n\n'
        'sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parents[2]))\n'
        'from zmux import runtime_info  # noqa: E402\n\n'
        'print(runtime_info.format_fingerprint(runtime_info.runtime_fingerprint()))\n'
    ),
}

_EXAMPLES_MARKER = ".examples_seeded"

LEGACY_RC_HOOK = True
"""``~/.zmuxrc`` is a legacy host-side hook, not the Alpine shell profile."""

ALPINE_PROFILE_FILENAME = ".profile"
"""Persistent Alpine login-shell profile stored in HOME_DIR and bound to /root."""

#: Legacy host-side startup file, executed line by line before Alpine starts.
#: Keep for migration and tests only. User-facing shell customisation belongs
#: in Alpine's ``~/.profile`` (``ALPINE_PROFILE_FILENAME``), not here.
RC_FILENAME = ".zmuxrc"


def legacy_rc_path(home: Path = HOME_DIR) -> Path:
    """Return the legacy host-side rc file path for migration diagnostics."""
    return Path(home) / RC_FILENAME


def read_rc_lines(home: Path = HOME_DIR) -> list:
    """Return executable legacy ``~/.zmuxrc`` lines.

    This hook feeds host-side Python compatibility code before Alpine starts.
    It is retained for migration; normal shell customisation belongs in
    Alpine's ``~/.profile``. Never raises: a broken or unreadable rc file must
    not stop the terminal from starting.
    """
    try:
        raw = legacy_rc_path(home).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return []
    lines = []
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            lines.append(stripped)
    return lines


def seed_examples(home: Path = HOME_DIR) -> Path | None:
    """Drop the example scripts into ``home/examples`` once (marker-guarded).

    Returns the examples dir when seeding happened, None when it was already
    done (or failed — onboarding must never break terminal startup).
    """
    try:
        if (home / _EXAMPLES_MARKER).exists():
            return None
        target = home / "examples"
        target.mkdir(parents=True, exist_ok=True)
        for name, content in EXAMPLE_SCRIPTS.items():
            (target / name).write_text(content, encoding="utf-8")
        (home / _EXAMPLES_MARKER).touch()
        return target
    except OSError:
        return None
