name: Dump Build Log
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: build
        working-directory: ./experimental/zmux-kotlin
        run: |
          gradle wrapper --gradle-version 8.7
          ./gradlew :app:assembleDebug || true
          cat app/build/reports/errors/*.txt || true
          cat app/build/reports/errors/*.log || true
          find . -name "*.log" | xargs cat || true
          echo "DUMPING STDOUT"
          ./gradlew :app:assembleDebug
